notifications:
  email: false

language: go

go:
  - 1.8

sudo: false

dist: trusty

install:
  - go get golang.org/x/tools/cmd/cover
  - make lint-deps

jobs:
  include:
    - stage: lint
      script: make lint
    - stage: Lint
      script: make lint
    - stage: Test unit and integration
      script: make test-unit-coverage
    - stage: Test e2e
      script: make test-e2e

cache:
  directories:
  - .ethereumtest
