# https://dependabot.com/docs/config-file/

version: 1
update_configs:
  # Keep go.mod and go.sum up to date, batching pull requests weekly
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
    default_assignees:
    - "cammellos"
    - "Samyoul"
    allowed_updates:
      - match:
        update_type: "security"
  - package_manager: "go:modules"
    directory: "/protocol"
    update_schedule: "weekly"
    default_assignees:
    - "cammellos"
    - "Samyoul"
    allowed_updates:
      - match:
        update_type: "security"
